# Generated by Django 3.1 on 2021-01-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='usage_time',
        ),
        migrations.AddField(
            model_name='post',
            name='components',
            field=models.TextField(blank=True, default='DEFAULT VALUE', max_length=355, null=True),
        ),
    ]
