# Generated by Django 3.1 on 2021-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210107_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='components',
            field=models.TextField(blank=True, max_length=355, null=True),
        ),
    ]
